services:

  db:
    image: postgres:16

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  web:
    build: .

    volumes:
      - static_volume:/app/staticfiles
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      -  static_volume:/app/staticfiles
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: